#!/usr/bin/env bash

sudo pacman -S \ 
        thunderbird \
	kicad \
        blender \
	gnumeric \
        featherpad \
	alsa-plugins \
	alsa-utils \
	breeze \
	celluloid \
	clipgrab \
	ffmpeg \
	firefox \
        gnome-calculator \
	gnome-disk-utility \
	gnome-screenshot \
	gufw \
	htop \
	lightdm \
	lightdm-gtk-greeter \
	lightdm-gtk-greeter-settings \
	man-db \
	man-pages \
        network-manager-applet \
	papirus-icon-theme \
	pavucontrol \
	pcmanfm \
	terminus-font \
	volumeicon \
	xed \
	xfce4-power-manager \
	xorg-server \
	xorg-xinit \
	xorg-xrandr \
	xterm \
	xvidcore \
